//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTCRM.MSGShengZhen {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://119.145.9.12/services/emsServices", ConfigurationName="MSGShengZhen.EmsServices")]
    public interface EmsServices {
        
        // CODEGEN: 消息 getUserInfoRequest 的包装命名空间(http://webservice.protal.ems.com)以后生成的消息协定与默认值(http://119.145.9.12/services/emsServices)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        CTCRM.MSGShengZhen.getUserInfoResponse getUserInfo(CTCRM.MSGShengZhen.getUserInfoRequest request);
        
        // CODEGEN: 消息 getSmsBalanceRequest 的包装命名空间(http://webservice.protal.ems.com)以后生成的消息协定与默认值(http://119.145.9.12/services/emsServices)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        CTCRM.MSGShengZhen.getSmsBalanceResponse getSmsBalance(CTCRM.MSGShengZhen.getSmsBalanceRequest request);
        
        // CODEGEN: 消息 sendSMSRequest 的包装命名空间(http://webservice.protal.ems.com)以后生成的消息协定与默认值(http://119.145.9.12/services/emsServices)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        CTCRM.MSGShengZhen.sendSMSResponse sendSMS(CTCRM.MSGShengZhen.sendSMSRequest request);
        
        // CODEGEN: 消息 batchSingleSendSMSRequest 的包装命名空间(http://webservice.protal.ems.com)以后生成的消息协定与默认值(http://119.145.9.12/services/emsServices)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        CTCRM.MSGShengZhen.batchSingleSendSMSResponse batchSingleSendSMS(CTCRM.MSGShengZhen.batchSingleSendSMSRequest request);
        
        // CODEGEN: 消息 getSmsReportRequest 的包装命名空间(http://webservice.protal.ems.com)以后生成的消息协定与默认值(http://119.145.9.12/services/emsServices)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        CTCRM.MSGShengZhen.getSmsReportResponse getSmsReport(CTCRM.MSGShengZhen.getSmsReportRequest request);
        
        // CODEGEN: 消息 getSmsMoRequest 的包装命名空间(http://webservice.protal.ems.com)以后生成的消息协定与默认值(http://119.145.9.12/services/emsServices)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        CTCRM.MSGShengZhen.getSmsMoResponse getSmsMo(CTCRM.MSGShengZhen.getSmsMoRequest request);
        
        // CODEGEN: 消息 getSmsFiltratesRequest 的包装命名空间(http://webservice.protal.ems.com)以后生成的消息协定与默认值(http://119.145.9.12/services/emsServices)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        CTCRM.MSGShengZhen.getSmsFiltratesResponse getSmsFiltrates(CTCRM.MSGShengZhen.getSmsFiltratesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserInfo", WrapperNamespace="http://webservice.protal.ems.com", IsWrapped=true)]
    public partial class getUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enterpriseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public getUserInfoRequest() {
        }
        
        public getUserInfoRequest(string enterpriseID, string loginName, string password) {
            this.enterpriseID = enterpriseID;
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserInfoResponse", WrapperNamespace="http://119.145.9.12/services/emsServices", IsWrapped=true)]
    public partial class getUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getUserInfoReturn;
        
        public getUserInfoResponse() {
        }
        
        public getUserInfoResponse(string getUserInfoReturn) {
            this.getUserInfoReturn = getUserInfoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsBalance", WrapperNamespace="http://webservice.protal.ems.com", IsWrapped=true)]
    public partial class getSmsBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enterpriseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public getSmsBalanceRequest() {
        }
        
        public getSmsBalanceRequest(string enterpriseID, string loginName, string password) {
            this.enterpriseID = enterpriseID;
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsBalanceResponse", WrapperNamespace="http://119.145.9.12/services/emsServices", IsWrapped=true)]
    public partial class getSmsBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getSmsBalanceReturn;
        
        public getSmsBalanceResponse() {
        }
        
        public getSmsBalanceResponse(string getSmsBalanceReturn) {
            this.getSmsBalanceReturn = getSmsBalanceReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMS", WrapperNamespace="http://webservice.protal.ems.com", IsWrapped=true)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enterpriseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string smsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string subPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string mobiles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string sendTime;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(string enterpriseID, string loginName, string password, string smsId, string subPort, string content, string mobiles, string sendTime) {
            this.enterpriseID = enterpriseID;
            this.loginName = loginName;
            this.password = password;
            this.smsId = smsId;
            this.subPort = subPort;
            this.content = content;
            this.mobiles = mobiles;
            this.sendTime = sendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSMSResponse", WrapperNamespace="http://119.145.9.12/services/emsServices", IsWrapped=true)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendSMSReturn;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(string sendSMSReturn) {
            this.sendSMSReturn = sendSMSReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="batchSingleSendSMS", WrapperNamespace="http://webservice.protal.ems.com", IsWrapped=true)]
    public partial class batchSingleSendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enterpriseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string[] batchSmsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string subPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string[] batchContent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string[] batchMobiles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string sendTime;
        
        public batchSingleSendSMSRequest() {
        }
        
        public batchSingleSendSMSRequest(string enterpriseID, string loginName, string password, string[] batchSmsId, string subPort, string[] batchContent, string[] batchMobiles, string sendTime) {
            this.enterpriseID = enterpriseID;
            this.loginName = loginName;
            this.password = password;
            this.batchSmsId = batchSmsId;
            this.subPort = subPort;
            this.batchContent = batchContent;
            this.batchMobiles = batchMobiles;
            this.sendTime = sendTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="batchSingleSendSMSResponse", WrapperNamespace="http://119.145.9.12/services/emsServices", IsWrapped=true)]
    public partial class batchSingleSendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string batchSingleSendSMSReturn;
        
        public batchSingleSendSMSResponse() {
        }
        
        public batchSingleSendSMSResponse(string batchSingleSendSMSReturn) {
            this.batchSingleSendSMSReturn = batchSingleSendSMSReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsReport", WrapperNamespace="http://webservice.protal.ems.com", IsWrapped=true)]
    public partial class getSmsReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enterpriseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public getSmsReportRequest() {
        }
        
        public getSmsReportRequest(string enterpriseID, string loginName, string password) {
            this.enterpriseID = enterpriseID;
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsReportResponse", WrapperNamespace="http://119.145.9.12/services/emsServices", IsWrapped=true)]
    public partial class getSmsReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getSmsReportReturn;
        
        public getSmsReportResponse() {
        }
        
        public getSmsReportResponse(string getSmsReportReturn) {
            this.getSmsReportReturn = getSmsReportReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsMo", WrapperNamespace="http://webservice.protal.ems.com", IsWrapped=true)]
    public partial class getSmsMoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enterpriseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        public getSmsMoRequest() {
        }
        
        public getSmsMoRequest(string enterpriseID, string loginName, string password) {
            this.enterpriseID = enterpriseID;
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsMoResponse", WrapperNamespace="http://119.145.9.12/services/emsServices", IsWrapped=true)]
    public partial class getSmsMoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getSmsMoReturn;
        
        public getSmsMoResponse() {
        }
        
        public getSmsMoResponse(string getSmsMoReturn) {
            this.getSmsMoReturn = getSmsMoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsFiltrates", WrapperNamespace="http://webservice.protal.ems.com", IsWrapped=true)]
    public partial class getSmsFiltratesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enterpriseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string content;
        
        public getSmsFiltratesRequest() {
        }
        
        public getSmsFiltratesRequest(string enterpriseID, string loginName, string password, string content) {
            this.enterpriseID = enterpriseID;
            this.loginName = loginName;
            this.password = password;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsFiltratesResponse", WrapperNamespace="http://119.145.9.12/services/emsServices", IsWrapped=true)]
    public partial class getSmsFiltratesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getSmsFiltratesReturn;
        
        public getSmsFiltratesResponse() {
        }
        
        public getSmsFiltratesResponse(string getSmsFiltratesReturn) {
            this.getSmsFiltratesReturn = getSmsFiltratesReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmsServicesChannel : CTCRM.MSGShengZhen.EmsServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmsServicesClient : System.ServiceModel.ClientBase<CTCRM.MSGShengZhen.EmsServices>, CTCRM.MSGShengZhen.EmsServices {
        
        public EmsServicesClient() {
        }
        
        public EmsServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmsServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmsServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmsServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTCRM.MSGShengZhen.getUserInfoResponse CTCRM.MSGShengZhen.EmsServices.getUserInfo(CTCRM.MSGShengZhen.getUserInfoRequest request) {
            return base.Channel.getUserInfo(request);
        }
        
        public string getUserInfo(string enterpriseID, string loginName, string password) {
            CTCRM.MSGShengZhen.getUserInfoRequest inValue = new CTCRM.MSGShengZhen.getUserInfoRequest();
            inValue.enterpriseID = enterpriseID;
            inValue.loginName = loginName;
            inValue.password = password;
            CTCRM.MSGShengZhen.getUserInfoResponse retVal = ((CTCRM.MSGShengZhen.EmsServices)(this)).getUserInfo(inValue);
            return retVal.getUserInfoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTCRM.MSGShengZhen.getSmsBalanceResponse CTCRM.MSGShengZhen.EmsServices.getSmsBalance(CTCRM.MSGShengZhen.getSmsBalanceRequest request) {
            return base.Channel.getSmsBalance(request);
        }
        
        public string getSmsBalance(string enterpriseID, string loginName, string password) {
            CTCRM.MSGShengZhen.getSmsBalanceRequest inValue = new CTCRM.MSGShengZhen.getSmsBalanceRequest();
            inValue.enterpriseID = enterpriseID;
            inValue.loginName = loginName;
            inValue.password = password;
            CTCRM.MSGShengZhen.getSmsBalanceResponse retVal = ((CTCRM.MSGShengZhen.EmsServices)(this)).getSmsBalance(inValue);
            return retVal.getSmsBalanceReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTCRM.MSGShengZhen.sendSMSResponse CTCRM.MSGShengZhen.EmsServices.sendSMS(CTCRM.MSGShengZhen.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public string sendSMS(string enterpriseID, string loginName, string password, string smsId, string subPort, string content, string mobiles, string sendTime) {
            CTCRM.MSGShengZhen.sendSMSRequest inValue = new CTCRM.MSGShengZhen.sendSMSRequest();
            inValue.enterpriseID = enterpriseID;
            inValue.loginName = loginName;
            inValue.password = password;
            inValue.smsId = smsId;
            inValue.subPort = subPort;
            inValue.content = content;
            inValue.mobiles = mobiles;
            inValue.sendTime = sendTime;
            CTCRM.MSGShengZhen.sendSMSResponse retVal = ((CTCRM.MSGShengZhen.EmsServices)(this)).sendSMS(inValue);
            return retVal.sendSMSReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTCRM.MSGShengZhen.batchSingleSendSMSResponse CTCRM.MSGShengZhen.EmsServices.batchSingleSendSMS(CTCRM.MSGShengZhen.batchSingleSendSMSRequest request) {
            return base.Channel.batchSingleSendSMS(request);
        }
        
        public string batchSingleSendSMS(string enterpriseID, string loginName, string password, string[] batchSmsId, string subPort, string[] batchContent, string[] batchMobiles, string sendTime) {
            CTCRM.MSGShengZhen.batchSingleSendSMSRequest inValue = new CTCRM.MSGShengZhen.batchSingleSendSMSRequest();
            inValue.enterpriseID = enterpriseID;
            inValue.loginName = loginName;
            inValue.password = password;
            inValue.batchSmsId = batchSmsId;
            inValue.subPort = subPort;
            inValue.batchContent = batchContent;
            inValue.batchMobiles = batchMobiles;
            inValue.sendTime = sendTime;
            CTCRM.MSGShengZhen.batchSingleSendSMSResponse retVal = ((CTCRM.MSGShengZhen.EmsServices)(this)).batchSingleSendSMS(inValue);
            return retVal.batchSingleSendSMSReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTCRM.MSGShengZhen.getSmsReportResponse CTCRM.MSGShengZhen.EmsServices.getSmsReport(CTCRM.MSGShengZhen.getSmsReportRequest request) {
            return base.Channel.getSmsReport(request);
        }
        
        public string getSmsReport(string enterpriseID, string loginName, string password) {
            CTCRM.MSGShengZhen.getSmsReportRequest inValue = new CTCRM.MSGShengZhen.getSmsReportRequest();
            inValue.enterpriseID = enterpriseID;
            inValue.loginName = loginName;
            inValue.password = password;
            CTCRM.MSGShengZhen.getSmsReportResponse retVal = ((CTCRM.MSGShengZhen.EmsServices)(this)).getSmsReport(inValue);
            return retVal.getSmsReportReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTCRM.MSGShengZhen.getSmsMoResponse CTCRM.MSGShengZhen.EmsServices.getSmsMo(CTCRM.MSGShengZhen.getSmsMoRequest request) {
            return base.Channel.getSmsMo(request);
        }
        
        public string getSmsMo(string enterpriseID, string loginName, string password) {
            CTCRM.MSGShengZhen.getSmsMoRequest inValue = new CTCRM.MSGShengZhen.getSmsMoRequest();
            inValue.enterpriseID = enterpriseID;
            inValue.loginName = loginName;
            inValue.password = password;
            CTCRM.MSGShengZhen.getSmsMoResponse retVal = ((CTCRM.MSGShengZhen.EmsServices)(this)).getSmsMo(inValue);
            return retVal.getSmsMoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CTCRM.MSGShengZhen.getSmsFiltratesResponse CTCRM.MSGShengZhen.EmsServices.getSmsFiltrates(CTCRM.MSGShengZhen.getSmsFiltratesRequest request) {
            return base.Channel.getSmsFiltrates(request);
        }
        
        public string getSmsFiltrates(string enterpriseID, string loginName, string password, string content) {
            CTCRM.MSGShengZhen.getSmsFiltratesRequest inValue = new CTCRM.MSGShengZhen.getSmsFiltratesRequest();
            inValue.enterpriseID = enterpriseID;
            inValue.loginName = loginName;
            inValue.password = password;
            inValue.content = content;
            CTCRM.MSGShengZhen.getSmsFiltratesResponse retVal = ((CTCRM.MSGShengZhen.EmsServices)(this)).getSmsFiltrates(inValue);
            return retVal.getSmsFiltratesReturn;
        }
    }
}
