<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MsgTem.aspx.cs" Inherits="CTCRM.admin.MsgTem" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <style>
        #gv_msg {
        width:98%;
        margin-top:10px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <div>
                类型:
                <asp:TextBox ID="tb_type" runat="server"></asp:TextBox>
                <asp:RadioButton ID="rbt_warn" runat="server" GroupName="1" Text="物流提醒" />
                <asp:RadioButton ID="rbt_send" runat="server" GroupName="1" Text="用户自选号码发送"  Checked="true"/>
            </div>
            <%--  二级标题: <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>--%>
            <div>
                内容:
                <asp:TextBox ID="tb_msg" runat="server" TextMode="MultiLine" Height="108px" Width="395px"></asp:TextBox>
                <asp:Button ID="bt_add" runat="server" Text="添加" OnClick="bt_add_Click" />
            </div>
            <asp:GridView ID="gv_msg" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" EnableModelValidation="True" AllowPaging="True" OnPageIndexChanging="gv_msg_PageIndexChanging" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="gv_msg_RowCancelingEdit" OnRowDeleting="gv_msg_RowDeleting" OnRowEditing="gv_msg_RowEditing" OnRowUpdating="gv_msg_RowUpdating">
                <Columns>
                    <asp:BoundField HeaderText="ID" DataField="id">
                    <ItemStyle Width="120px" HorizontalAlign="Center" />
                    </asp:BoundField>
                    <asp:BoundField HeaderText="类型" DataField="page_type" >
                    <ItemStyle HorizontalAlign="Center" />
                    </asp:BoundField>
                    <asp:BoundField HeaderText="短信内容" DataField="msg_content" >
                    <ItemStyle HorizontalAlign="Center" />
                    </asp:BoundField>
                </Columns>
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            </asp:GridView>
        </div>
    </form>
</body>
</html>
